#!/bin/bash

DF="/usr/bin/df"

usage() {
	echo 'usage: dfp [OPTION] DEVICE...'
	echo
	echo '  -p    print given prefix at the begin of each line'
	echo '  -h    display this help and exit'
	exit
}

[[ $1 ]] && [[ $1 != "-h" ]] || usage

args=$@

if [[ $1 == -p ]]; then
	prefix="$2"
	args=${@:3}
fi

for device in $args; do
	if ! [[ "$($DF $device)" ]]; then
		usage
	fi
done

for device in $args; do
	size="$($DF $device --output=size | tail --lines=+2)"
	avail="$($DF $device --output=avail | tail --lines=+2)"
	used="$((size - avail))"
	
	availh="$($DF -h $device --output=avail | tail --lines=+2)"
	sizeh="$($DF -h $device --output=size | tail --lines=+2)"
	misc="$availh$sizeh"
	title="$prefix$device"

	pbar -n $used $size "$title" "$misc"
done
